from tkinter import *
import pytz
from datetime import datetime
import pygame
timezone=pytz.timezone('US/Pacific')
timezone2=pytz.timezone('Asia/Hong_Kong')
timezone3=pytz.timezone('Australia/Victoria')
print(pytz.all_timezones)

i4=pygame.image.load("C:/Users/ubons/Downloads/canadianflag.png")
i5=pygame.transform.scale(i4,(260,175))
pygame.image.save(i5,"C:/Users/ubons/Downloads/canadianflag1.png")
i8=pygame.image.load("C:/Users/ubons/Downloads/ChineseFlag.png")
i9=pygame.transform.scale(i8,(260,200))
pygame.image.save(i9,"C:/Users/ubons/Downloads/ChineseFlag1.png")
i10=pygame.image.load("C:/Users/ubons/Downloads/australianflag.png")
i11=pygame.transform.scale(i10,(260,175))
pygame.image.save(i11,"C:/Users/ubons/Downloads/australianflag1.png")
master=Tk()
x=StringVar()
y=StringVar()
z=StringVar()
w=StringVar()
master.title("frames")
F1=Frame(master)
F1.grid(row=1,column=1)
F2=Frame(master)
F2.grid(row=2,column=1)
F3=Frame(master)
F3.grid(row=1,column=2)
F4=Frame(master)
F4.grid(row=2,column=2)
i1=PhotoImage(file="C:/Users/ubons/Downloads/USflag.png")
usflag=Label(F1,image=i1)
usflag.grid(row=2,column=1)
i2=PhotoImage(file="C:/Users/ubons/Downloads/ChineseFlag1.png")
chineseflag=Label(F2,image=i2)
chineseflag.grid(row=2,column=1)
i3=PhotoImage(file="C:/Users/ubons/Downloads/canadianflag1.png")
canadianflag=Label(F3,image=i3)
canadianflag.grid(row=2,column=1)
i7=PhotoImage(file="C:/Users/ubons/Downloads/australianflag1.png")
canadianflag=Label(F4,image=i7)
canadianflag.grid(row=2,column=1)
L1=Label(F1,textvariable=x)
L1.grid(row=3,column=1)
L2=Label(F2,textvariable=y)
L2.grid(row=3,column=1)
L3=Label(F3,textvariable=z)
L3.grid(row=3,column=1)
L4=Label(F4,textvariable=w)
L4.grid(row=3,column=1)
while True:
    current=datetime.now(timezone)
    current2=datetime.now(timezone2)
    current3=datetime.now(timezone3)
    final_time=current.strftime('%Y-%m-%d-%I:%M:%S %p %Z')
    final_time2=current2.strftime('%Y-%m-%d-%I:%M:%S %p %Z')
    final_time3=current3.strftime('%Y-%m-%d-%I:%M:%S %p %Z')
    z.set(final_time)
    x.set(final_time)
    y.set(final_time2)
    w.set(final_time3)
    master.update()
master.mainloop()
